name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install dev, build, and lint
      run: |
        npm ci
        npm run build --if-present
        npm run lint --if-present
    - name: npm install prod, exec
      run: |
        rm -rf node_modules/
        npm i --production
        echo -e "^C^C^C" | prod/index.js
      env:
        CI: true
