# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish

on:
  push:
    branches:
      - master # Change this to your default branch

jobs:

  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    # outputs:
    #   status: ${{ steps.ID.conclusion }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - name: Wait for CI action to succeed
        uses: fountainhead/action-wait-for-check@7ee38294c9e2ee911a1db471a8095ee7e00d4663
              # This is tagged version v1.0.0, but do not use version tags
              # https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: ci-status
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 180
      - name: CI action build OK
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: exit 0
      - name: CI action build FAIL
        if: steps.wait-for-build.outputs.conclusion != 'success'
        run: exit 1

  test-version:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.haschanged.outputs.status }}
    steps:
      - uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@7d67b971df2c119e8dab599b302b311d5db2e8f7
              # This is tagged version v1.5.0, but do not use version tags
              # https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        with:
          diff-search: true
      - name: Return if version has been updated
        id: haschanged
        run: echo "##[set-output name=status;]${{ steps.check.outputs.changed || false }}"

  publish-npm:
    needs: test-version
    runs-on: ubuntu-latest
    if: needs.test-version.outputs.status == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@06e0830ea83eea10ed4a62654eeaedafb8bf50fc
              # This is tagged version v1.3.3, but do not use version tags
              # https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings

  publish-gpr:
    needs: test-version
    runs-on: ubuntu-latest
    if: needs.test-version.outputs.status == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Update package name
        run: |
          sudo npm install -g json
          REGISTRY_NAME=`json registryNames.github -f package.json`
          json -I -f package.json -e this.name=\"$REGISTRY_NAME\"
      - name: Publishing new package
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-aur:
    #needs: test-version
    runs-on: ubuntu-latest
    #if: needs.test-version.outputs.status == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Clone aur repository
        run: |
          mkdir "$HOME/.ssh/"
          echo -e "${{ secrets.AUR_AUTH_KEY }}" > "$HOME/.ssh/aur"
          sudo apt install ssh -y
          ssh-add "$HOME/.ssh/aur"
          echo -e "[user]\nemail = theo.cousinet@epitech.eu\nname = Theo\n" > "$HOME/.gitconfig"
          git clone --depth=1 ssh://aur@aur.archlinux.org/blih_cli-git.git
      - name: Update package name
        run: |
          echo "ok"
      - name: Publishing new package
        run: |
          cd blih_cli-git/
          echo "hello" > test.txt
          git add -A
          git commit -m "test github action"
          git push
